empty:
	svnadmin dump svn-test/repos/testrepo > empty.dump

firstcommit:
	./scripts/firstcommit.sh > firstcommit.dump

svn_replace:
	./scripts/svn_replace.sh > svn_replace.dump

svn_rename:
	./scripts/svn_rename.sh > svn_rename.dump

svn_multi_file_delete:
	./scripts/svn_multi_file_delete.sh > svn_multi_file_delete.dump

simple_branch_and_merge:
	./scripts/simple_branch_and_merge.sh > simple_branch_and_merge.dump
